apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: BASE_64_CERT
    server: SERVER_URL
  name: CLUSTER_NAME
contexts:
- context:
    cluster: my-cluster.ap-south-1.eksctl.io
    user: devops@my-cluster.ap-south-1.eksctl.io
  name: devops@my-cluster.ap-south-1.eksctl.io
current-context: devops@my-cluster.ap-south-1.eksctl.io
kind: Config
preferences: {}
users:
- name: devops@my-cluster.ap-south-1.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - token
      - -i
      - my-cluster
      command: aws-iam-authenticator
      env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      - name: AWS_DEFAULT_REGION
        value: ap-south-1
      provideClusterInfo: false
